package com.app.vehicledocdb.vehicledocdb.greenDaoModel;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig requirementDaoConfig;
    private final DaoConfig incidentDaoConfig;

    private final RequirementDao requirementDao;
    private final IncidentDao incidentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        requirementDaoConfig = daoConfigMap.get(RequirementDao.class).clone();
        requirementDaoConfig.initIdentityScope(type);

        incidentDaoConfig = daoConfigMap.get(IncidentDao.class).clone();
        incidentDaoConfig.initIdentityScope(type);

        requirementDao = new RequirementDao(requirementDaoConfig, this);
        incidentDao = new IncidentDao(incidentDaoConfig, this);

        registerDao(Requirement.class, requirementDao);
        registerDao(Incident.class, incidentDao);
    }
    
    public void clear() {
        requirementDaoConfig.getIdentityScope().clear();
        incidentDaoConfig.getIdentityScope().clear();
    }

    public RequirementDao getRequirementDao() {
        return requirementDao;
    }

    public IncidentDao getIncidentDao() {
        return incidentDao;
    }

}
