package com.app.vehicledocdb.vehicledocdb.greendaomodel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INCIDENT".
 */
public class Incident {

    private Long id;
    private String incidentName;
    private String address;
    private String date;
    private Double price;

    public Incident() {
    }

    public Incident(Long id) {
        this.id = id;
    }

    public Incident(Long id, String incidentName, String address, String date, Double price) {
        this.id = id;
        this.incidentName = incidentName;
        this.address = address;
        this.date = date;
        this.price = price;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIncidentName() {
        return incidentName;
    }

    public void setIncidentName(String incidentName) {
        this.incidentName = incidentName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

}
