package com.app.vehicledocdb.vehicledocdb.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "REQUIREMENT".
 */
public class Requirement {

    private Long id;
    private String name;
    private String endDate;

    public Requirement() {
    }

    public Requirement(Long id) {
        this.id = id;
    }

    public Requirement(Long id, String name, String endDate) {
        this.id = id;
        this.name = name;
        this.endDate = endDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

}
